version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      # As senhas agora são lidas do arquivo .env
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: 'wordpress'
      # A senha agora é lida do arquivo .env
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DB_NAME: 'wordpress'
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wordpress-network

volumes:
  db_data:

networks:
  wordpress-network: